apiVersion: v1
kind: Pod
metadata:
  labels:
  name: webserver-liveness
spec:
  containers:
  - image: nginx:1.14
    name: webserver
    ports:
    - containerPort: 80
      protocol: TCP

    livenessProbe:
      httpGet:
        path: /
        port: 80

